# Generated by Django 4.1.2 on 2022-10-07 14:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_alter_post_media"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="media",
        ),
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(blank=True, upload_to="images"),
        ),
        migrations.AddField(
            model_name="post",
            name="upload_video",
            field=models.FileField(
                blank=True,
                upload_to="videos",
                validators=[django.core.validators.FileExtensionValidator(["mp4"])],
            ),
        ),
    ]
