# Generated by Django 4.1.2 on 2022-10-07 16:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_alter_post_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="image",
        ),
        migrations.RemoveField(
            model_name="post",
            name="upload_video",
        ),
        migrations.AddField(
            model_name="post",
            name="upload_file",
            field=models.FileField(
                blank=True,
                upload_to="videos",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["mp4", "jpeg", "png", "jpg"]
                    )
                ],
            ),
        ),
    ]
