# Generated by Django 4.1.2 on 2022-10-08 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0010_like"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="likes",
        ),
        migrations.DeleteModel(
            name="Like",
        ),
    ]
