# Generated by Django 4.1.7 on 2023-03-11 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Bookmarks",
        ),
    ]
