# Generated by Django 4.1.7 on 2023-03-02 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="industrysummary",
            name="insight",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
