# Generated by Django 4.1.2 on 2022-10-22 10:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BankRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("email", models.CharField(max_length=100)),
                ("mobile", models.CharField(max_length=10)),
                ("age", models.IntegerField()),
                ("gender", models.IntegerField(choices=[(0, "male"), (1, "female")])),
                (
                    "hobbies",
                    models.CharField(
                        choices=[
                            ("Reading", "Reading"),
                            ("Movies", "Movies"),
                            ("Music", "Music"),
                            ("Games", "Games"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "bank",
                    models.CharField(
                        choices=[
                            ("SBI", "SBI"),
                            ("RBI", "RBI"),
                            ("PNB", "PNB"),
                            ("Maharashtra Bank", "Maharashtra Bank"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "password",
                    models.CharField(
                        max_length=14,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid password",
                                message="Password - 8 characters - 1 Capital letter, 1 special character , 1 number must. Min 8 characters max 14 characters",
                                regex="^(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9])(?=.*?[#?!@$%^&*-]).{8,}$",
                            )
                        ],
                    ),
                ),
            ],
        ),
    ]
