# Generated by Django 4.1.2 on 2022-10-22 12:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("form", "0002_alter_bankregistration_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bankregistration",
            name="age",
            field=models.IntegerField(
                validators=[django.core.validators.MaxValueValidator(3)]
            ),
        ),
    ]
