# Generated by Django 4.1.2 on 2022-10-22 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("form", "0003_alter_bankregistration_age"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bankregistration",
            name="age",
            field=models.IntegerField(),
        ),
    ]
