# Generated by Django 4.1.2 on 2022-10-22 13:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("form", "0004_alter_bankregistration_age"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bankregistration",
            name="age",
            field=models.IntegerField(
                default=1,
                validators=[
                    django.core.validators.MaxValueValidator(150),
                    django.core.validators.MinValueValidator(1),
                ],
            ),
        ),
    ]
