# Generated by Django 4.1.5 on 2023-01-22 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_account_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="country",
            field=models.CharField(
                choices=[("In", "India"), ("En", "England")], max_length=100
            ),
        ),
    ]
