# Generated by Django 4.1.1 on 2023-02-16 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_remove_account_username_alter_account_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="address",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="account",
            name="phone",
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
